### ISSUE TITLE
Function components cannot be given refs

### ISSUE THREAD

**Issue by danvk** [jcoreio/material-ui-popup-state#11]
I started getting this warning when I updated to React 16.8:

    Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Here's the full stack trace:

![image](https://user-images.githubusercontent.com/98301/64367772-d5ecbb80-cfe6-11e9-8b0f-f2d256b910f5.png)

Any suggestions? It looks like @piotrf over in https://github.com/jcoreio/material-ui-popup-state/issues/9#issuecomment-500022593 was having a similar issue.

**Comment by jedwards1211** [comment]
I'll look into it, meanwhile let's meditate on how terrible and annoying forward refs are.

**Comment by jedwards1211** [comment]
@danvk can you give some example code that causes the issue?  I'm not seeing it in the demos.

**Comment by jedwards1211** [comment]
Is some component being naughty and using `cloneElement` to inject a `ref` property?

**Comment by jedwards1211** [comment]
or are you trying to do `<HoverMenu ref={...}>`?  `HoverMenu` and `HoverPopover` aren't currently designed to be ref-able.  I guess I should probably `forwardRef` them since people will try  to do that, but really there are probably better ways to do whatever one would try to do with a ref on a `Menu` or `Popover`.

**Comment by jedwards1211** [comment]
@danvk okay I released 1.4.1...does it fix your issue?

**Comment by danvk** [comment]
Thanks for the update @jedwards1211. Unfortunately it did not fix the error for us. It looks like the fix had something to do with `HoverMenu`, which we're not using.

Here's an extract of our code. I can try to put together a more complete repro for you if this isn't enough. It's in TypeScript.

```ts
import Icon from '@material-ui/core/Icon';
import IconButton from '@material-ui/core/IconButton';
import ListItemText from '@material-ui/core/ListItemText';
import Menu from '@material-ui/core/Menu';
import MenuItem from '@material-ui/core/MenuItem';
import {Theme, withStyles} from '@material-ui/core/styles';
import Tooltip from '@material-ui/core/Tooltip';
import _ from 'lodash';
import PopupState, {bindMenu, bindTrigger, PopupStateType} from 'material-ui-popup-state';
import * as React from 'react';

// Most of this is based on https://jcoreio.github.io/material-ui-popup-state/
// When material-ui supports Cascading Menus directly, we should use that.
const ParentPopupState = React.createContext<PopupStateType>(null!);

const CascadingHoverMenus = (props: {
  files: _.Dictionary<string[]>;
  onClick: (file: string) => void;
  idName: string;
}) => {
  const {files, onClick} = props;
  const fileTypes = _.sortBy(Object.keys(files));

  return (
    <PopupState variant="popover" popupId="demoMenu">
      {(popupState: PopupStateType) => {
        const menuItems = fileTypes.map(fileType => {
          const fileItems = files[fileType].map(file => (
            <MenuItem
              key={file}
              onClick={() => {
                popupState.close();
                onClick(file);
              }}>
              {file}
            </MenuItem>
          ));

          return (
            <Submenu popupId={fileType} key={fileType} title={fileType}>
              {fileItems}
            </Submenu>
          );
        });

        return (
          <>
            <Tooltip title="Download" placement="bottom">
              <IconButton id={props.idName} {...bindTrigger(popupState)}>
                <Icon style={icons.SMALL_ICON_STYLE}>cloud_download</Icon>
              </IconButton>
            </Tooltip>
            <ParentPopupState.Provider value={popupState}>
              <Menu
                {...bindMenu(popupState)}
                anchorOrigin={{vertical: 'bottom', horizontal: 'left'}}
                transformOrigin={{vertical: 'top', horizontal: 'left'}}
                getContentAnchorEl={null}>
                {menuItems}
              </Menu>
            </ParentPopupState.Provider>
          </>
        );
      }}
    </PopupState>
  );
};

const submenuStyles = (theme: Theme) => ({
  menu: {
    top: -theme.spacing(),
  },
  title: {
    flexGrow: 1,
  },
  moreArrow: {
    marginRight: theme.spacing(-1),
  },
});

interface SubmenuProps {
  popupId: string;
  title: string;
  classes: Record<string, string>;
  children: JSX.Element[];
}

const Submenu = withStyles(submenuStyles)(
  ({classes, title, popupId, children, ...props}: SubmenuProps) => {
    return (
      <ParentPopupState.Consumer>
        {(parentPopupState: PopupStateType) => {
          return (
            <PopupState variant="popover" popupId={popupId} parentPopupState={parentPopupState}>
              {(popupState: PopupStateType) => {
                return (
                  <ParentPopupState.Provider value={popupState}>
                    <MenuItem {...bindTrigger(popupState)} selected={popupState.isOpen}>
                      <ListItemText className={classes.title}>{title}</ListItemText>
                      <icons.ChevronRight className={classes.moreArrow} />
                    </MenuItem>
                    <Menu
                      {...bindMenu(popupState)}
                      className={classes.menu}
                      anchorOrigin={{vertical: 'top', horizontal: 'right'}}
                      transformOrigin={{vertical: 'top', horizontal: 'left'}}
                      getContentAnchorEl={null}
                      {...props}>
                      {children}
                    </Menu>
                  </ParentPopupState.Provider>
                );
              }}
            </PopupState>
          );
        }}
      </ParentPopupState.Consumer>
    );
  },
);
```

**Comment by jedwards1211** [comment]
Still unable to tell what would be causing it, what is `icons`?  There's no binding for that identifier in the code sample

**Comment by jedwards1211** [comment]
Btw I'd advise
```js
const fileTypes = React.useMemo(() => _.sortBy(Object.keys(files)), [files]);
```

**Comment by jedwards1211** [comment]
Okay it's this issue: https://github.com/mui-org/material-ui/issues/15903
I really don't know why my demo isn't triggering this issue but you'll need to wrap `Submenu` in `React.forwardRef` and pass the ref to the `MenuItem`.  I'll update the demo even though I'm not seeing the error there...

**Comment by danvk** [comment]
Thanks @jedwards1211. I've confirmed that this fixes the issue in my code.
